### ISSUE TITLE
Line must be greater than or equal to 1, got -1

### ISSUE THREAD

**Issue by SorenHolstHansen** [CaptainCodeman/sveltekit-example#10]
I tried running the repo, but got 
```
Line must be greater than or equal to 1, got -1

TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/.../sveltekit-example/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65405:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/.../sveltekit-example/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:65474:22)
    at /Users/.../sveltekit-example/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66413:34
    at String.replace (<anonymous>)
    at /Users/.../sveltekit-example/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66403:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/.../sveltekit-example/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66402:10)
    at instantiateModule (/Users/.../sveltekit-example/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66547:28)
```
I am using yarn, if that makes a difference

**Comment by CaptainCodeman** [comment]
I think there are still issues with the Firebase 9 SDK - if you pin it to the 9.0.0 version it works.

**Comment by SorenHolstHansen** [comment]
That worked, thanks!

**Comment by dnotes** [comment]
I had this same issue, which brought me here. I later found [Ben McCann's comment](https://github.com/firebase/firebase-js-sdk/issues/4846#issuecomment-954396213) in the Firebase SDK queue. Adding the suggested config to svelte.config.js seems to solve the problems with firebase/auth. PR seems hardly worth the trouble but I think this is the workaround for now.

```
diff --git a/svelte.config.js b/svelte.config.js
index da8701d..29f7dff 100644
--- a/svelte.config.js
+++ b/svelte.config.js
@@ -19,6 +19,9 @@ const config = {
                target: '#svelte',
 
                vite: {
+      ssr: {
+        external: ['whatwg-url', 'node-fetch']
+      },
                        build: {
                                sourcemap: true,
                        },
```
